name: Newman CLI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman + htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # --- PR: ejecución simple en consola ---
      - name: Run Collection (PR validation)
        if: github.event_name == 'pull_request'
        run: newman run "POC.postman_collection.json"

      # --- Master: ejecución con reporte HTML ---
      - name: Run Collection with HTML Report
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p test_results
          DATE=$(date +'%Y-%m-%d')
          REPORT_NAME="report_${DATE}.html"
          echo "REPORT_NAME=$REPORT_NAME" >> $GITHUB_ENV
          newman run "POC.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export "test_results/$REPORT_NAME"

      - name: Upload HTML report artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: test_results/${{ env.REPORT_NAME }}
